version: '3.1'

services:
  comment_app:
    container_name: post_app
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - post_db
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    networks:
      - demo_net
  comment_db:
    container_name: post_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    networks:
      - demo_net

networks:
  demo_net:
    driver: bridge